"""saas architecture

Revision ID: dc6b1bd462cb
Revises: d7a8ba4485e8
Create Date: 2026-06-01 01:15:04.128433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc6b1bd462cb'
down_revision = 'd7a8ba4485e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('metadata_schema', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('platform_fee_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('paystack_subaccount', sa.String(length=100), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_fees', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)

    op.create_table('ticket_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_categories_event_id'), ['event_id'], unique=False)

    op.create_table('platform_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fee_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_transactions_tenant_id'), ['tenant_id'], unique=False)

    op.drop_table('event_sections')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('net_to_owner', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_bookings_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('sport_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('sport_meta', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'sport_categories', ['sport_id'], ['id'])
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_column('match_teams')
        batch_op.drop_column('competition')
        batch_op.drop_column('category')

    with op.batch_alter_table('seat_holds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.alter_column('seat_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_foreign_key(None, 'ticket_categories', ['category_id'], ['id'])

    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.alter_column('pos_x',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('pos_y',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('seat_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_foreign_key(None, 'ticket_categories', ['category_id'], ['id'])
        batch_op.drop_column('scanned')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_venues_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_column('layout_config')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('layout_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_venues_tenant_id'))
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scanned', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('seat_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.alter_column('pos_y',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('pos_x',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    with op.batch_alter_table('seat_holds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('seat_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('quantity')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('competition', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('match_teams', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_events_tenant_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_public')
        batch_op.drop_column('sport_meta')
        batch_op.drop_column('sport_id')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bookings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_idempotency_key'))
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('net_to_owner')
        batch_op.drop_column('platform_fee')
        batch_op.drop_column('tenant_id')

    op.create_table('event_sections',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('section_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('available_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='event_sections_event_id_fkey'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name='event_sections_section_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='event_sections_pkey')
    )
    with op.batch_alter_table('platform_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_transactions_tenant_id'))

    op.drop_table('platform_transactions')
    with op.batch_alter_table('ticket_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_categories_event_id'))

    op.drop_table('ticket_categories')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))

    op.drop_table('tenants')
    op.drop_table('sport_categories')
    # ### end Alembic commands ###
